[package]
name = "example-surveys"
version = "0.6.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/barafael/elicitor"
publish = false

[dependencies]
elicitor = { path = "../elicitor" }
anyhow = "1"
